### ISSUE TITLE
nodejs_npm not idempotent? 

### ISSUE THREAD

**Issue by adrianmoisey** [redguide/nodejs#115]
I'm installing `sinopia` using https://github.com/BarthV/sinopia-cookbook/blob/master/recipes/sinopia.rb#L9-L12, but no matter what I do, the chef decides to install `sinopia` on each run, even though i'm specifying the version.

From what I can tell this should be idempotent. I can't seem to figure out what's wrong.

**Comment by BarthV** [comment]
I've done some debug :
```
* execute[install NPM package sinopia] action run

== STARTING DEBUG ==
new_resource.package = sinopia
npm_package_installed?(new_resource.package, new_resource.version, new_resource.path, new_resource.npm_token) = false

(!list.nil?) = true
list.key?(package) = true
version_valid?(list, package, version) = true
url_valid?(list, package) = false

npm_package_installed? false
== END ==
```

It seems that `url_valid?` is not working properly.
I'll see what's wrong here.

**Comment by BarthV** [comment]
bug confirmed.
We're working on a fix (better way to detect and compare installed version)

**Comment by skewart** [comment]
I'm running into this bug too.   A fix would be hugely appreciated.  

I'm happy to help out if you'd be open to a PR with a quick fix that just checks if the url is valid (though, to be honest, I'm not entirely sure how or why an invalid URL would get into this "resolved" field in the first place; so maybe there's more than just generic `url =~ URI::regexp` validity checking that the function is supposed to perform).

**Comment by kemra102** [comment]
Curiously we see this problem when `chef-client` runs as a daemon but if you call `chef-client` at the CLI the issue does not occur.

Any update on when we can expect to see this fixed?

**Comment by hrak** [comment]
@kemra102 Also seeing this on manual runs (bower in my case)

```
  * nodejs_npm[bower] action install
    * execute[install NPM package bower] action run
      - execute npm install  -global bower
```

**Comment by sgtcoolguy** [comment]
Here's the commit which introduced the bug: https://github.com/redguide/nodejs/commit/2b1c055c01cc46ea8cf928464d09b74c5de065cf

Basically, before it would just check that the version matched, but that commit also has it checking that the "url" is valid for the package. I'm not sure why the check was added, but with npm 2.15.9 and 3.10.8 my output structure doesn't match what url_valid? is looking for. Specifically they're looking for a 'resolved' property's value to include 'url'. I don't know if they're assuming that the resolved property would be an array holding an 'url' string entry, or it's looking for a child 'url' property? In any case, for my npm output it gives a string value for 'resolved' property, the value being a String URL.

I think the easiest fix would be to simply remove the url_valid? call altogether since it's not really doing anything other than introducing this bug. The more correct fix may be to check the resolved URL value from he JSON output against the URL of the package about to be installed to see if it's changed at all, and if it has to then assume the package/version the user wants isn't installed (and to re-install).

**Comment by tas50** [comment]
New release will fix this
