### ISSUE TITLE
Dependencies error on AWS OpsWorks

### ISSUE THREAD

**Issue by swaroopsm** [redguide/nodejs#133]
I am using this cookbook and the default recipe to install NodeJS on AWS OpsWorks. But I get the following error:

```
================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: yum-epel

Expanded Run List:
------------------
* nodejs

Platform:
---------
x86_64-linux
```

**Comment by mattdeboard** [comment]
I am assuming you are not using `yum` for package management. 

The problem you describe happens because in the `metadata.json` file, it has several platform-specific dependencies specified. Chef does not allow conditional dependencies. If a recipe is included (e.g. `include_recipe yum_epel` or whatever) then the cookbook author needs to include it as a `depends` line in the metadata. It's a limitation of Chef's metadata.

I just removed those dependencies from metadata and the run list resolves fine. (This is assuming you're not actually using `yum`. If you are then you should make sure the cookbooks in the metadata dependencies are installed.)

**Comment by Pankaj-Pippin** [comment]
Hi,

What do u means by removed it from meta data can u show the code from where you removed it ? 
I am using Amazon linux .

Metadata

  "dependencies": {
    **"yum-epel": ">= 0.0.0",**
    "build-essential": ">= 0.0.0",
    "ark": ">= 0.0.0",
    "apt": ">= 2.9.1",
    "homebrew": ">= 0.0.0"
  },

**Comment by tas50** [comment]
This should be resolved in the latest version of the cookbook without the JSON. Feel free to open it up if you're still having the issue with that release
