### ISSUE TITLE
Cannot install npm modules

### ISSUE THREAD

**Issue by endorama** [redguide/nodejs#63]
Hello! I've starting using this cookbook but I'm facing a problem that I wasn't able to overcome.

I'm using a vagrant machine ( box is ubuntu/trusty64 ). Everything works except for npm module installation.

This is the excerpt from mi node.json file ( loaded by chef-solo ):
```
{
  "run_list": [
    "nodejs::npm", [...]
  ],
  "nodejs": {
    "npm_packages": [
      { "name": "sails" },
      { "name": "grunt-cli" }
    ]
  },
  {...}
}
```

What am I doing wrong? I want to install sails and grunt-cli module globally.

Thanks for your help

**Comment by BarthV** [comment]
Hi @endorama ,

First ```node['nodejs']['npm_packages']``` is currently only used in ```nodejs::default``` recipe.
If you only specify ```nodejs::npm``` in your run list, you'll have to call ```nodejs_npm``` LWRP by your own.

Then you point a second issue : ```nodejs::npm``` is doing nothing if you select embedded install method (which is default behaviour). I'll push an update for this later. We made many changes in ```nodejs::nodejs``` recipe, that's why we can still got this kind of mistake.

thanks

**Comment by BarthV** [comment]
second point fixed by #68 & #69

**Comment by endorama** [comment]
Thanks for the clarification!

Could you please confirm that this node.json should work as expected?

```json
{
  "run_list": [
    "nodejs", [...]
  ],
  "nodejs": {
    "npm_packages": [
      { "name": "sails" },
      { "name": "grunt-cli" }
    ]
  },
  {...}
}
```

**Comment by BarthV** [comment]
Yes, this should be good with this conf

**Comment by endorama** [comment]
It works! :) Thanks for your help, closing.
